### ISSUE TITLE
Differences to original Gorilla paper..

### ISSUE THREAD

**Issue by burmanm** [facebookincubator/beringei#17]
Would it be possible to document the possible differences to the original Gorilla paper with potentially some explanation also why you opted to modify the original algorithm/implementation?

For example the timestamp encoding difference, where the implementation uses the "0" value also to improve encoding efficiency ([-64,64]), instead of the paper described [-63,64] where 0 value is ignored.

And also the reasoning, I assume it's because performance wasn't an issue and the bit efficiency was more important than one additional branch in the decoding phase.

**Comment by jteller** [comment]
We won't put a _lot_ of effort into this, because the people currently working on the code, the main author of the paper (me), and much of the code's original author are disjoint sets of people. I'll put some comments in the code for the things that I know have changed though.

The particular difference you pointed out looks to be due to author error. In other words, my bad. My reading of the code was off of reality.

**Comment by scottfranklin** [comment]
To clarify a bit, there have been no changes to the compression algorithm since the paper was written. Any differences you see are errors in the paper.
Migration from one compression algorithm to another is a bit of a pain, and so we haven't spent much time looking for improvements to @tuomaspelkonen's original version.

Were we *have* made significant changes is in the service itself, focused primarily around scaling and operating the system. It would take awhile to dig through 2 years of commit logs, but for example, Beringei will now [deduplicate timeseries](https://github.com/facebookincubator/beringei/blob/17a6c2d44783ddbef68cdc44619ef824d63215e8/beringei/lib/BucketStorage.cpp#L124-L138) within each shard when cycling buckets, and it will now [operate in a degraded mode](https://github.com/facebookincubator/beringei/blob/17a6c2d44783ddbef68cdc44619ef824d63215e8/beringei/lib/SimpleMemoryUsageGuard.cpp#L16-L20) as it runs out of memory, rather than allowing itself to crash.

**Comment by cgthayer** [comment]
@burmanm  -63 can fit into 7 bits so that was probably the intent whereas once decompressed it makes sense to use a regular 8-bit byte (short) or a signed long... is there a particular line of code you're thinking of?
I'm looking at https://github.com/facebookincubator/beringei/blob/master/beringei/lib/TimeSeriesStream.cpp#L143

**Comment by burmanm** [comment]
@cgthayer Well, I was actually referring to the lines above it (134-137). Yes, 7 bits can store [-64,-1] and [0,63], but as the value can't be 0 (it will fall to previous if clause), you can reuse that and think it as [1,64]. 

And completely unrelated, no need for long as the maximum delta is 14 bits in a single block (in this implementation).

**Comment by dgryski** [comment]
I had two fixes in my implementation of the paper:
https://github.com/dgryski/go-tsz/commit/2d496e2f4e151a0f31ef9679d26bf07cd30508eb

and

https://github.com/dgryski/go-tsz/commit/918e888e1d33760f5ab18e41cab3857c0037abfe

**Comment by mlgood** [comment]
Are there any remaining questions here?

**Comment by mlgood** [comment]
It seems like this has been mostly resolved, so I'm going to close the issue.  Please feel free to open a new issue if there are any additional questions, and thanks for the interest in beringei!
