### ISSUE TITLE
Is it possible to configure value for data retention? (I found in a document that data will be cached for 26hours). 

### ISSUE THREAD

**Issue by vmukumar** [facebookincubator/beringei#29]

**Comment by scottfranklin** [comment]
Beringei breaks data into time slices. By default it stores 13 x 2hr complete slices plus the one currently receiving data, resulting in 26-28hrs of retention depending on the current time.

You can adjust this with the [--buckets and --bucket_size](https://github.com/facebookincubator/beringei/blob/master/beringei/service/BeringeiServiceHandler.cpp#L29-L33) flags.

There's a bit of a trade-off here. Increasing the bucket size adds some overhead due to the necessity of holding on to a full extra bucket to meet the required retention. Adding more buckets adds overhead to each timeseries to track the extra buckets.

We found that, while the compression ratio does improve as buckets get bigger, the gains are fairly minimal after the first two hours, so that's not as much of a factor. Though when copying data out of Beringei and into longer-term storage, we do typically recompress the data into larger blocks (12+ hours) to reduce the number of them.

**Comment by vmukumar** [comment]
Thank you

**Comment by mszone** [comment]
Thank you Scott for your response. 
Quick clarification. Can you please provide what are the trade-offs and overheads by increasing the bucket size or number of buckets. We need more than 8 days worth of data for setting up the week-over-week alerts. If it is stored in long-term storage, the retrieval of the data from long-term storage will be slower. So please advise what will be best to keep more than 8 days of data in memory.

**Comment by jteller** [comment]
More buckets at the same bucket-size means you get more retention.

Increasing bucket size while decreasing the number of buckets (so you get the same retention) means that you get slightly better compression within a bucket. However, since only "full" buckets are dropped from the end of Beringei, it means that the "extra bucket" you need to keep around to make sure you always have at least 8 days of data will be larger.

As an example - assume your bucket size is 24 hours, and you always need at least 8 days of data. That means you will have 8 finalized (completed) buckets at all times. This means that just before finalization, you're actually storing 9 full days of data, or an extra 12.5% of data than what you need. However, if your bucket size is 2 hours, then to do 8 days of data you need 192 finalized buckets. Just before finalization, you are storing 8 days + 2 hours of data, or just over 0.5% more data than you need.

We see small improvements in per-bucket compression ratios moving from 2 hour buckets to 24h buckets - but it's not that large, and depends on your data set's characteristics.

There are probably also some query latency effects when you are storing and returning lots of buckets in queries - but we haven't run that analysis yet.
