### ISSUE TITLE
Can you introduce how Beringei supports cluster?

### ISSUE THREAD

**Issue by scutojr** [facebookincubator/beringei#31]

**Comment by linuxfood** [comment]
Assuming you mean how does Beringei scale, it does this by sharding the data across many nodes.

When you setup Beringei, you generate a configuration file that's read by both the server and the clients. This file contains, amongst a little bit of other information, the shard map. This defines which shards belong to which instances (host:port) of Beringei. It's important that the clients and servers agree on this configuration otherwise you'll get inconsistent results and dropped data. Beringei tries to be resilient to transient inconsistencies, such as if you're updating the shard map to account for new/removed servers, by retrying reads and writes during these periods by issuing retries when it detects this condition.

Hopefully this answers your question!

**Comment by scutojr** [comment]
It solves my problem and thanks for your answer.
