### ISSUE TITLE
how to install on centos/rhel

### ISSUE THREAD

**Issue by firstsko** [facebookincubator/beringei#33]
how to install on centos/rhel

**Comment by linuxfood** [comment]
Hi! Thanks for your interest in Beringei. 

Installing on CentOS/Redhat is much the same as Ubuntu. You'll need all the equivalent dependencies as listed in setup_ubuntu.sh. Right now we only officially support Ubuntu 16.10 since we have limited resources. We'd rather it work well, and easily on one platform than overextending ourselves too soon. You'll likely need to build a number of the dependencies by hand, however, since it typically lags behind Ubuntu by quite a lot.

**Comment by at15** [comment]
@firstsko you can try vagrant (which is a ubuntu vm that use the `setup_ubuntu.sh`), it works pretty well on Fedora, so I guess it should work well on centos/rhel.
